// Code generated by cmd/reset; DO NOT EDIT.

package models

// Reset clears Metrics while retaining slice, map and pointer allocations.
func (rs *Metrics) Reset() {
	if rs == nil {
		return
	}
	rs.ID = ""
	rs.MType = ""
	if rs.Delta != nil {
		(*rs.Delta) = 0
	}
	if rs.Value != nil {
		(*rs.Value) = 0
	}
	rs.Hash = ""
}
