// Command reset generates Reset methods for structs marked with // generate:reset.
package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

//go:embed reset.tmpl
var resetTemplate string

const generatedHeader = "// Code generated by cmd/reset; DO NOT EDIT.\n"

func main() {
	root, err := moduleRoot()
	if err == nil {
		err = generate(root)
	}
	if err != nil {
		log.Fatal(err)
	}
}

func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get working directory: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		} else if !os.IsNotExist(err) {
			return "", fmt.Errorf("find go.mod: %w", err)
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func marked(group *ast.CommentGroup) bool {
	if group != nil {
		for _, comment := range group.List {
			if strings.TrimSpace(strings.TrimPrefix(comment.Text, "//")) == "generate:reset" {
				return true
			}
		}
	}
	return false
}

func generate(root string) error {
	pkgs, err := packages.Load(&packages.Config{
		Dir: root,
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports | packages.NeedDeps,
	}, "./...")
	if err != nil {
		return fmt.Errorf("load packages: %w", err)
	}
	if packages.PrintErrors(pkgs) != 0 {
		return fmt.Errorf("cannot generate Reset methods: packages contain errors")
	}
	// Prepare every file before writing, so a type error cannot leave partial output.
	outputs := make(map[string][]byte)
	for _, pkg := range pkgs {
		g := generator{pkg: pkg, imports: make(map[string]string)}
		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				group, ok := decl.(*ast.GenDecl)
				if !ok || group.Tok != token.TYPE {
					continue
				}
				for _, spec := range group.Specs {
					ts := spec.(*ast.TypeSpec)
					if !marked(ts.Doc) && !(len(group.Specs) == 1 && marked(group.Doc)) {
						continue
					}
					if _, ok := ts.Type.(*ast.StructType); !ok || ts.Assign.IsValid() {
						return fmt.Errorf("%s: generate:reset requires a defined struct", pkg.Fset.Position(ts.Pos()))
					}
					named := pkg.TypesInfo.Defs[ts.Name].Type().(*types.Named)
					for i := 0; i < named.NumMethods(); i++ {
						method := named.Method(i)
						if method.Name() == "Reset" && filepath.Base(pkg.Fset.Position(method.Pos()).Filename) != "reset.gen.go" {
							return fmt.Errorf("%s already has a Reset method", named.Obj().Name())
						}
					}
					g.method(named)
				}
			}
		}
		if len(g.methods) == 0 {
			continue
		}
		path := filepath.Join(filepath.Dir(pkg.CompiledGoFiles[0]), "reset.gen.go")
		if data, err := os.ReadFile(path); err == nil {
			if !bytes.HasPrefix(data, []byte(generatedHeader)) {
				return fmt.Errorf("refusing to overwrite non-generated file %s", path)
			}
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("read %s: %w", path, err)
		}
		data, err := g.source()
		if err != nil {
			return fmt.Errorf("format %s: %w", path, err)
		}
		outputs[path] = data
	}
	for path, data := range outputs {
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

type generator struct {
	pkg     *packages.Package
	methods []resetMethod
	imports map[string]string
	index   int
}

func (g *generator) typeName(t types.Type) string {
	return types.TypeString(t, func(pkg *types.Package) string {
		if pkg == g.pkg.Types {
			return ""
		}
		if alias, ok := g.imports[pkg.Path()]; ok {
			return alias
		}
		alias := fmt.Sprintf("resetpkg%d", len(g.imports))
		g.imports[pkg.Path()] = alias
		return alias
	})
}

// resetMethod and resetOperation describe code; reset.tmpl owns its rendering.
type resetMethod struct {
	Name       string
	Receiver   string
	Operations []resetOperation
}

type resetOperation struct {
	Kind     string
	Expr     string
	Value    string
	Type     string
	Index    string
	Children []resetOperation
}

func (g *generator) method(named *types.Named) {
	name := named.Obj().Name()
	receiverType := name
	if params := named.TypeParams(); params.Len() > 0 {
		var names []string
		for i := 0; i < params.Len(); i++ {
			names = append(names, params.At(i).Obj().Name())
		}
		receiverType += "[" + strings.Join(names, ", ") + "]"
	}
	method := resetMethod{Name: name, Receiver: receiverType}
	fields := named.Underlying().(*types.Struct)
	for i := 0; i < fields.NumFields(); i++ {
		field := fields.Field(i)
		if field.Name() != "_" {
			method.Operations = append(method.Operations, g.reset("rs."+field.Name(), field.Type()))
		}
	}
	g.methods = append(g.methods, method)
}

func (g *generator) reset(expr string, t types.Type) resetOperation {
	op := resetOperation{Expr: expr}
	switch underlying := t.Underlying().(type) {
	case *types.Basic:
		op.Kind, op.Value = "basic", "0"
		switch {
		case underlying.Info()&types.IsBoolean != 0:
			op.Value = "false"
		case underlying.Info()&types.IsString != 0:
			op.Value = `""`
		case underlying.Kind() == types.UnsafePointer:
			op.Value = "nil"
		}
	case *types.Pointer:
		op.Kind = "pointer"
		op.Children = []resetOperation{g.reset("(*"+expr+")", underlying.Elem())}
	case *types.Slice:
		op.Kind = "slice"
	case *types.Map:
		op.Kind = "map"
	case *types.Struct:
		// A runtime assertion also finds methods generated in this same run.
		op.Kind, op.Type = "struct", g.typeName(t)
	case *types.Array:
		op.Kind, op.Index = "array", fmt.Sprintf("i%d", g.index)
		g.index++
		op.Children = []resetOperation{g.reset(expr+"["+op.Index+"]", underlying.Elem())}
	default:
		op.Kind, op.Type = "zero", g.typeName(t)
	}
	return op
}

type resetImport struct {
	Alias string
	Path  string
}

func (g *generator) source() ([]byte, error) {
	paths := make([]string, 0, len(g.imports))
	for path := range g.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	imports := make([]resetImport, 0, len(paths))
	for _, path := range paths {
		imports = append(imports, resetImport{Alias: g.imports[path], Path: path})
	}
	tmpl, err := template.New("reset").Parse(resetTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse reset template: %w", err)
	}
	data := struct {
		Header  string
		Package string
		Imports []resetImport
		Methods []resetMethod
	}{generatedHeader, g.pkg.Name, imports, g.methods}
	var source bytes.Buffer
	if err := tmpl.Execute(&source, data); err != nil {
		return nil, fmt.Errorf("execute reset template: %w", err)
	}
	return format.Source(source.Bytes())
}
